//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGEM_Db_JSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class features
    {
        public int feature_id { get; set; }
        public int part_id { get; set; }
        public string feature_type { get; set; }
        public string label { get; set; }
        public Nullable<int> start_pos { get; set; }
        public Nullable<int> end_pos { get; set; }
        public Nullable<int> direction_is_reverse { get; set; }
    
        public virtual parts parts { get; set; }
    }
}
