//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGEM_Db_JSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class parts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parts()
        {
            this.features = new HashSet<features>();
        }
    
        public int part_id { get; set; }
        public string part_name { get; set; }
        public string part_type { get; set; }
        public string status { get; set; }
        public string nickname { get; set; }
        public string short_desc { get; set; }
        public string description { get; set; }
        public Nullable<int> sequence_length { get; set; }
        public string sequence { get; set; }
        public string notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<features> features { get; set; }
    }
}
